version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependency
    reviewers:
      - ktr0731
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependency
    reviewers:
      - ktr0731
